---
- name: restart pulse as user
  systemd:
    name: pipewire-pulse.service
    scope: user
    state: restarted
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
