---
- name: Install i3
  pacman:
    name:
      - i3-wm
      - i3blocks
      - i3status
    state: present

- name: Install py3status
  pacman: name=py3status state=present

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF

- include: rofi.yml
- include: misc.yml
- include: picom.yml
- include: py3status.yml
- include: i3-save-tree.yml
- include: polybar.yml
