---

- name: Install visidata and libraries
  pacman:
    name:
      - python-xlrd
      - python-pandas
      - python-openpyxl
      - python-pandas
      - python-requests
      - python-xlrd
    state: present

- name: Push visidata desktop file
  copy:
    src: visidata.desktop
    dest: /usr/local/share/applications/visidata.desktop

- name: Verify mimeapps.list exists
  file:
    path: /etc/xdg/mimeapps.list
    state: touch

- name: Set visidata as default application for relevant mimetypes
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^text/csv=', line: 'text/csv=visidata.desktop' }
    - { regexp: '^text/tab-separated-values=', line: 'text/tab-separated-values=visidata.desktop' }
