---
- include_tasks: beets.yml
- include_tasks: abcde.yml
- include_tasks: imagemagick.yml
- include_tasks: inkscape.yml
- include_tasks: gimp.yml
- include_tasks: gthumb.yml
- include_tasks: feh.yml
- include_tasks: imv.yml
- include_tasks: teiler.yml
- include_tasks: flac2all.yml
- include_tasks: darktable.yml
- include_tasks: qcode.yml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
    state: present

- name: Install Metadata Anonymisation Toolkit
  pacman:
    name: mat2
    state: present
  tags:
    - mat

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present

- name: Install sxiv
  pacman:
    name: sxiv
    state: present

- name: Install svgcleaner
  pacman:
    name: svgcleaner
    state: present

- name: Install flameshot
  pacman:
    name: flameshot
    state: present

- name: Install digikam
  pacman:
    name: digikam
    state: present
