---
- name: Install GNUradio
  pacman:
    name: gnuradio
    state: present

- name: Install hamlib
  pacman:
    name: hamlib
    state: present

- include_tasks: rtl-sdr.yml
#- include_tasks: radio_mgmt.yml
- include_tasks: radio_ops.yml
